
import React from 'react';
import { DesignResponse, ProductSpec } from '../types';

interface DesignDisplayProps {
  data: DesignResponse;
  onDownload: () => void;
}

const DesignDisplay: React.FC<DesignDisplayProps> = ({ data, onDownload }) => {
  const { spec, images, selfCheck, implementationCode, marketingPitchUrl, videoUrl } = data;
  
  // Use corrected spec if available, otherwise original
  const finalSpec = selfCheck.correctedSpec || spec;

  // Safe guards
  const constraints = finalSpec.constraints || {};
  const requirements = finalSpec.keyRequirements || [];
  const parts = finalSpec.partsList || [];
  const steps = finalSpec.assemblyOrImplementationSteps || [];
  const issues = selfCheck.issues || [];

  return (
    <div className="max-w-6xl mx-auto pb-20 space-y-8">
      
      {/* Header Actions */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center bg-white p-6 rounded-2xl shadow-sm border border-slate-200 sticky top-20 z-10 bg-opacity-95 backdrop-blur-sm">
        <div>
            <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight">{finalSpec.productName || "Untitled Product"}</h1>
            <div className="flex items-center gap-2 mt-1">
                <span className="px-2 py-0.5 rounded text-xs font-bold bg-blue-100 text-blue-700 uppercase tracking-wide">{finalSpec.productType}</span>
                <span className="text-xs text-slate-400">Generated by Gemini 3</span>
            </div>
        </div>
        <div className="mt-4 sm:mt-0 flex gap-3">
            <button 
                onClick={onDownload}
                className="bg-green-600 hover:bg-green-700 text-white px-6 py-2.5 rounded-xl font-semibold shadow-lg shadow-green-200 transition-all flex items-center gap-2 hover:-translate-y-0.5"
            >
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4"></path></svg>
                Download Packet
            </button>
        </div>
      </div>
      
      {/* Grid Layout */}
      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8">
        
        {/* Left Column: Spec Details (8 cols) */}
        <div className="lg:col-span-8 space-y-8">
            
            {/* Summary */}
            <section className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100">
                <h3 className="text-lg font-bold text-slate-800 mb-4 flex items-center gap-2">
                    <span className="text-blue-500">📄</span> Executive Summary
                </h3>
                <p className="text-slate-600 leading-relaxed text-lg">{finalSpec.summary || "No summary generated."}</p>
            </section>
            
            {/* Code Implementation Block */}
            {implementationCode && (
                <section className="bg-slate-900 rounded-2xl shadow-lg border border-slate-800 overflow-hidden flex flex-col max-h-[500px]">
                    <div className="flex items-center justify-between px-6 py-3 bg-slate-800 border-b border-slate-700 flex-shrink-0">
                        <div className="flex items-center gap-2">
                             <span className="w-3 h-3 rounded-full bg-red-500"></span>
                             <span className="w-3 h-3 rounded-full bg-yellow-500"></span>
                             <span className="w-3 h-3 rounded-full bg-green-500"></span>
                             <span className="ml-3 text-sm font-mono text-slate-400 font-bold">
                                {implementationCode.language === 'cpp' ? 'firmware.ino' : 
                                 implementationCode.language === 'python' ? 'controller.py' : 'App.tsx'}
                             </span>
                        </div>
                        <span className="text-xs text-slate-500 uppercase font-bold tracking-wider">Auto-Generated Prototype</span>
                    </div>
                    <div className="p-6 overflow-y-auto custom-scrollbar flex-grow">
                        <pre className="font-mono text-sm text-green-400 leading-relaxed whitespace-pre-wrap">
                            <code>{implementationCode.code}</code>
                        </pre>
                    </div>
                    <div className="px-6 py-3 bg-slate-800/50 text-xs text-slate-400 border-t border-slate-800 italic flex-shrink-0">
                        {implementationCode.explanation}
                    </div>
                </section>
            )}

            {/* Constraints & Requirements */}
            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                <section className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                    <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wide mb-4">Constraints</h3>
                    <ul className="space-y-3 text-sm text-slate-700">
                        {Object.entries(constraints).map(([k, v]) => (
                            <li key={k} className="flex flex-col"><span className="font-semibold capitalize text-slate-900">{k.replace(/([A-Z])/g, ' $1')}</span> <span className="text-slate-500">{v}</span></li>
                        ))}
                    </ul>
                </section>
                <section className="bg-white p-6 rounded-2xl shadow-sm border border-slate-100">
                    <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wide mb-4">Requirements</h3>
                    <ul className="space-y-2 text-sm text-slate-700">
                        {requirements.map((r, i) => <li key={i} className="flex gap-2"><span className="text-blue-500">•</span> {r}</li>)}
                    </ul>
                </section>
            </div>

            {/* Parts List */}
            <section className="bg-white rounded-2xl shadow-sm border border-slate-100 overflow-hidden">
                <div className="p-6 border-b border-slate-100 bg-slate-50/50">
                    <h3 className="text-lg font-bold text-slate-800">Bill of Materials</h3>
                </div>
                <div className="overflow-x-auto">
                    <table className="w-full text-left text-sm">
                        <thead className="bg-slate-50 text-slate-500 font-medium">
                            <tr>
                                <th className="p-4 pl-6">Component</th>
                                <th className="p-4">Description</th>
                                <th className="p-4">Tech/Material</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100">
                            {parts.map((part, idx) => (
                                <tr key={idx} className="hover:bg-slate-50 transition-colors">
                                    <td className="p-4 pl-6 font-semibold text-slate-800">{part.name}</td>
                                    <td className="p-4 text-slate-600">{part.description}</td>
                                    <td className="p-4 text-slate-500 italic">{part.materialOrTech || "-"}</td>
                                </tr>
                            ))}
                        </tbody>
                    </table>
                </div>
            </section>

             {/* Assembly */}
             <section className="bg-white p-8 rounded-2xl shadow-sm border border-slate-100">
                <h3 className="text-lg font-bold text-slate-800 mb-6">Implementation Steps</h3>
                <div className="space-y-6">
                    {steps.map((step, i) => (
                        <div key={i} className="flex gap-4">
                            <div className="flex-shrink-0 w-8 h-8 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-sm">{i + 1}</div>
                            <p className="text-slate-700 mt-1">{step}</p>
                        </div>
                    ))}
                </div>
            </section>

        </div>

        {/* Right Column: Visuals & Audit (4 cols) */}
        <div className="lg:col-span-4 space-y-8">
            
            {/* Veo Video */}
            {videoUrl && (
                <section className="bg-black rounded-2xl overflow-hidden shadow-lg border border-slate-900 group relative">
                    <div className="absolute top-3 left-3 z-10 bg-black/50 backdrop-blur-md px-2 py-1 rounded text-[10px] font-bold text-white border border-white/20 uppercase">
                        Generated with Veo
                    </div>
                    <video 
                        src={videoUrl} 
                        controls 
                        className="w-full h-auto aspect-video object-cover"
                        poster={images[0]?.url} // Use first image as poster
                    />
                    <div className="p-4 bg-slate-900">
                        <h4 className="text-white font-bold text-sm">Product Commercial</h4>
                        <p className="text-slate-500 text-xs mt-1">AI-generated cinematic concept video</p>
                    </div>
                </section>
            )}

            {/* Audio Pitch */}
            {marketingPitchUrl && (
                <div className="bg-gradient-to-br from-indigo-500 to-purple-600 p-6 rounded-2xl shadow-lg text-white">
                     <span className="text-xs font-bold text-indigo-200 uppercase tracking-wider block mb-3">Shark Tank Pitch (AI Audio)</span>
                     <audio controls src={marketingPitchUrl} className="w-full h-10 accent-white opacity-90 hover:opacity-100 transition-opacity" />
                     <p className="text-xs text-indigo-100 mt-3 italic opacity-80">"Generated by Gemini 2.5 Flash TTS"</p>
                </div>
            )}
            
            {/* Diagrams */}
            <section className="space-y-6">
                <h3 className="text-sm font-bold text-slate-400 uppercase tracking-wide">Blueprints (Nano Banana Pro)</h3>
                {images.length > 0 ? (
                    images.map((img, idx) => (
                        <div key={idx} className="bg-white p-3 rounded-2xl shadow-sm border border-slate-200 group hover:shadow-md transition-all">
                            <div className="relative aspect-[4/3] bg-slate-100 rounded-xl overflow-hidden mb-3 border border-slate-100">
                                <img src={img.url} alt={img.title} className="w-full h-full object-contain mix-blend-multiply" />
                            </div>
                            <div className="px-1">
                                <p className="font-bold text-slate-800 text-sm leading-tight">{img.title}</p>
                                <p className="text-xs text-slate-400 mt-1 uppercase tracking-wider">{img.diagramType}</p>
                            </div>
                        </div>
                    ))
                ) : (
                    <div className="bg-white p-6 rounded-xl shadow-sm border border-slate-200 text-center text-slate-400 italic">
                        No diagrams generated.
                    </div>
                )}
            </section>

            {/* Self-Check Report */}
            <section className="bg-slate-900 text-slate-300 p-6 rounded-2xl shadow-xl relative overflow-hidden">
                <div className="absolute top-0 right-0 p-4 opacity-10">
                    <svg className="w-32 h-32" fill="currentColor" viewBox="0 0 24 24"><path d="M9 12l2 2 4-4m6 2a9 9 0 11-18 0 9 9 0 0118 0z"></path></svg>
                </div>
                <h3 className="text-lg font-bold text-white mb-6 flex items-center gap-2 relative z-10">
                    <span className="w-2 h-2 bg-green-500 rounded-full animate-pulse"></span>
                    AI Verification Report
                </h3>
                
                {issues.length === 0 ? (
                    <div className="text-green-400 flex items-start gap-3 relative z-10">
                        <svg className="w-6 h-6 flex-shrink-0" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path strokeLinecap="round" strokeLinejoin="round" strokeWidth="2" d="M5 13l4 4L19 7"></path></svg>
                        <p className="text-sm font-medium">All systems go. The generated diagrams strictly follow the engineering constraints.</p>
                    </div>
                ) : (
                    <div className="space-y-4 relative z-10">
                        <p className="text-yellow-400 text-xs font-bold uppercase tracking-widest">Inconsistencies Resolved</p>
                        <ul className="space-y-3">
                            {issues.map((issue, i) => (
                                <li key={i} className="flex gap-3 items-start text-sm">
                                    <span className="text-yellow-500 mt-0.5">⚠️</span>
                                    <span className="opacity-90 leading-snug">{issue}</span>
                                </li>
                            ))}
                        </ul>
                    </div>
                )}
                <div className="mt-6 pt-4 border-t border-slate-800 text-xs text-slate-500 relative z-10">
                    Gemini 3 Self-Correction Loop
                </div>
            </section>
        </div>

      </div>
    </div>
  );
};

export default DesignDisplay;
